name: Build and Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Install poetry and pipx
      run: |
        pip install poetry && pip install pipx
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.14'
        # cache: 'uv'   # caching for uv not supported

    - name: Install package managers
      run: |
        pip install pipx && pip install uv && pipx install uv && pipx install hatchling && uv sync

    - name: Install Dependencies
      run: uv sync --all-extras

    - name: Run just check
      run: uv run make check
